apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-downstream-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-downstream-app
  template:
    metadata:
      labels:
        app: nodejs-downstream-app
    spec:
      containers:
      - name: nodejs-downstream-app
        image: dezkoat13/serv2:v2
        ports:
        - containerPort: 3000
