apiVersion: v1
kind: Service
metadata:
  name: nodejs-downstream-service
spec:
  type: LoadBalancer
  selector:
    app: nodejs-downstream-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
